site_name: Finko Docs
site_url: https://sebbouez.github.io/finko-docs/
theme:
  name: material
  extra_css:
    - stylesheets/custom.css
  language: en
  features:
    - navigation.tabs
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: custom
extra_css:
  - stylesheets/custom.css      
nav:
  - Home: index.md
  - User Guide:
    - Getting started: guides/get-started.md
    - Account view: guides/account-view.md
    - Filter transactions: guides/filter-account-transactions.md
    - Recurring transactions: guides/recurring-transactions.md
    - Budgets: guides/budgets.md
    - Reports: guides/reports.md
  - Updates: changelog.md
  - Privacy: privacy.md
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sebbouez/finko-docs