site_name: Finko Docs
site_url: https://sebbouez.github.io/finko-docs/
theme:
  name: material
  extra_css:
    - stylesheets/custom.css
  language: en
  features:
    - navigation.tabs
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: custom
extra_css:
  - stylesheets/custom.css      
nav:
  - Home: index.md
  - User Guide: guide.md
  - Privacy: privacy.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sebbouez/finko-docs